export { default as Cafeteria } from './Cafeteria'
export { default as Home } from './Home'
export { default as Homeworks } from './Homeworks'
export { default as Recoveries } from './Recoveries'
export { default as Schedule } from './Schedule'
export { default as Settings } from './Settings'
export { default as Setup } from './Setup'
